# Site settings
title: Super Awesome Site
email: hopmann@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Super awesome description of my new site here. I can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in my feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chopmann.github.io/" # the base hostname & protocol for your site
twitter_username: c_hopmann
github_username:  chopmann

# Build settings
markdown: kramdown
exclude:
- heisenbug.net.iml
- bower_components
- bower.json
- package.json
- node_modules
- Rakefile
- Gemfile
- Gemfile.lock
- Gruntfile.coffee
- readme.md
- scss